name: ROS2 CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install ROS2
        run: |
          sudo apt update && sudo apt install curl gnupg2 lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list
          sudo apt update
          sudo apt install ros-humble-desktop
          sudo apt install ros-dev-tools

      - name: Install dependencies
        run: |
          source /opt/ros/humble/setup.bash
          sudo apt update
          sudo rosdept init
          rosdep update
          rosdep install --from-paths src --ignore-src --rosdistro humble -y

      - name: Build the package
        run: |
          source /opt/ros/humble/setup.bash
          colcon build

      - name: Run tests
        run: |
          source /opt/ros/humble/setup.bash
          colcon test
